name: Pull-Requests Check

on: [pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 20.x

      - name: Install dependencies and run Eslint
        run: |
          npm i
          npm run lint
